// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzkTlWPrF_b2i2SVQ-AhXl-2ZhWlnnG4U',
    appId: '1:572991678414:web:2587cc954ebb95c033ed9f',
    messagingSenderId: '572991678414',
    projectId: 'tickr-eaeca',
    authDomain: 'tickr-eaeca.firebaseapp.com',
    storageBucket: 'tickr-eaeca.firebasestorage.app',
    measurementId: 'G-FVZFSBL0H1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Gc5N1c7rwT3Anj0ynAxM59GQeh070z8',
    appId: '1:572991678414:ios:6ab4e10e97a740c233ed9f',
    messagingSenderId: '572991678414',
    projectId: 'tickr-eaeca',
    storageBucket: 'tickr-eaeca.firebasestorage.app',
    iosBundleId: 'com.camverge.tickr',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz_bK0zwl9roTRpi0GwFYsNR1psXZ_4oo',
    appId: '1:572991678414:android:fa636d9d3656448733ed9f',
    messagingSenderId: '572991678414',
    projectId: 'tickr-eaeca',
    storageBucket: 'tickr-eaeca.firebasestorage.app',
  );

}